version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_nestjs
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: nestjs_app
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017/nestdb
    networks:
      - default

volumes:
  mongo_data:
    driver: local
